config/routes.rb
Rails.application.routes.draw do

  resources :enrollments
  resources :lessons
  
  devise_for :users

  resources :courses do
    resources :enrollments, only: [:new, :create]
  end
  
  resources :users, only: [:index, :edit, :show, :update]

  get 'home/activity'

  root to: 'home#index'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord

  # Relationship
  belongs_to :course
  belongs_to :user

  # Validations
  validates :user, :course, presence: true

  validates_uniqueness_of :user_id, scope: :course_id # user can't be subscribed to the same course twice
  validates_uniqueness_of :course_id,  scope: :user_id # user can't be subscribed to the same course twice

  def to_s
    user.to_s + " " + course.to_s
  end


  protected
  validate :cant_subscribe_to_own_course
  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present?
        if user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[show edit update destroy]
  before_action :set_course, only: [:new, :create]


  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    if @course.price > 0
      flash[:alert] = "You can not access paid courses yet."
      redirect_to new_course_enrollments_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrollment now!"
    end
  
    #  @enrollment = Enrollment.new(enrollment_params)
  #  @enrollment.price = @enrollment.course.price
#
  #  respond_to do |format|
  #    if @enrollment.save
  #      format.html { redirect_to @enrollment, notice: "Enrollment was successfully created." }
  #      format.json { render :show, status: :created, location: @enrollment }
  #    else
  #      format.html { render :new, status: :unprocessable_entity }
  #      format.json { render json: @enrollment.errors, status: :unprocessable_entity }
  #    end
  #  end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end

    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    def enrollment_params
      params.require(:enrollment).permit(:rating, :review)
      # params.require(:enrollment).permit(:course_id, :user_id, :rating, :review)
    end
    
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating
    = f.input :review

  .form-actions
    = f.button :submit

app/views/enrollments/edit.html.haml
- content_for :title do
  ScolGeek
  \|
  Editing
  = @enrollment.to_s

.card
  .card-header
    %h3
      .fa.fa-lock-open
        Editing Enrollment
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', @enrollment
    \|
    = link_to 'Back', enrollments_path

app/views/enrollments/index.html.haml
- content_for :title do
  ScolGeek
  \|
  All Enrollments

%h3
  .text-center
    Enrollments
    .badge.badge-info
      = @enrollments.count

%p
.table-responsive
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        %th Course
        %th User
        %th Rating
        %th Review
        %th Price
        %th
        %th
        %th

    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.course
          %td= enrollment.user
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_currency(enrollment.price)
          %td= link_to 'Show', enrollment
          %td= link_to 'Edit', edit_enrollment_path(enrollment)
          %td= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to  new_enrollment_path, class: 'btn btn-primary btn-sm' do
  .fa.fa-plus
  New Enrollment

app/views/enrollments/new.html.haml
- content_for :title do
  ScolGeek
  \|
  New Enrollment

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
        = link_to @course.title, course_enrollments_path(@course)
        %hr
        .fa.fa-lock-open
        Buy Course
    .card-body
      = form_tag course_enrollments_path(@course) do
        = submit_tag "Pay #{@course.price}" , class: "btn btn-sm btn-success"
    /= render 'form'
  .card-footer
    = link_to 'Back', enrollments_path

app/views/enrollments/show.html.haml
%p#notice= notice

%p
  %b Course:
  = @enrollment.course
%p
  %b User:
  = @enrollment.user
%p
  %b Rating:
  = @enrollment.rating
%p
  %b Review:
  = @enrollment.review
%p
  %b Price:
  = @enrollment.price

= link_to 'Edit', edit_enrollment_path(@enrollment)
\|
= link_to 'Back', enrollments_path