config/routes.rb
Rails.application.routes.draw do

  resources :enrollments
  resources :lessons
  
  devise_for :users

  resources :courses do
    resources :enrollments, only: [:new, :create]
  end
  
  resources :users, only: [:index, :edit, :show, :update]

  get 'home/activity'

  root to: 'home#index'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  # FriendlyId
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_rich_text :content
  belongs_to :course
  validates :title, :content, :course, presence: true

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }


  def to_s
    title
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
    authorize @lesson
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    #@course = Course.friendly.find(params[:course_id])
  end

  # GET /lessons/1/edit
  def edit
    authorize @lesson
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    #@course = Course.friendly.find(params[:course_id])
    #@lesson.course_id = @course.id
    authorize @lesson

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: "Lesson was successfully updated." }
       # format.html { redirect_to course_lesson_path(@course, @lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      #format.html { redirect_to course_path(@course), notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.friendly.find(params[:id])
      #@course = Course.friendly.find(params[:course_id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :content, :course_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    /= f.input :content
    = f.label :content
    = f.rich_text_area :content
    %small= f.error :content, class: 'text-danger'
    %p
    = f.association :course
    %p
    /= f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}



  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    .far.fa-check-square
    = link_to lesson.title, lesson_path(lesson)
  - if policy(lesson).show?
    .card-body
      = lesson.content
      = lesson.course
  - if policy(lesson).edit?
    .card-footer
      = link_to 'Edit', edit_lesson_path(lesson), class: "btn btn-warning btn-sm"
      = link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"
%p

app/views/lessons/edit.html.haml
- content_for :title do
  ScolGeek
  \/
  Course
  = @course.title
  \/
  Editing lesson
  = @lesson.title

.card
  .card-header
    %h3
      .far.fa-check-square
      Editing
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', @lesson
    \|
    = link_to 'Back', lessons_path

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.content
        %td= lesson.course
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
- content_for :title do
  ScolGeek
  \/
  Course
  \/
  New lesson
  = @lesson.title

.card
  .card-header
    %h3
      .far.fa-check-square
      New lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', lessons_path

app/views/lessons/show.html.haml
- content_for :title do
  ScolGeek
  \/
  Course
  \/
  Editing lesson
  = @lesson.title

%p
= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@lesson.course)
\/
= link_to @lesson.title, lesson_path(@lesson)
%p



= render 'lessons/lesson', lesson: @lesson

= link_to 'Back to course', course_path(@lesson.course)