config/routes.rb
Rails.application.routes.draw do

  resources :enrollments
  resources :lessons
  
  devise_for :users

  resources :courses do
    resources :enrollments, only: [:new, :create]
  end
  
  resources :users, only: [:index, :edit, :show, :update]

  get 'home/activity'

  root to: 'home#index'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  def index
    #if params[:title]
     # @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive_keys
    #else
    # @q = Course.ransack(params[:q])
    # @courses = @q.result.includes(:user)

    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    # @courses = @ransack_courses.result.includes(:user)
    @pagy, @courses = pagy( @ransack_courses.result.includes(:user))
    #end
  end

  def show
    @lessons = @course.lessons
  end

  def new
    @course = Course.new
    authorize @course
  end

  def edit
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(
        :title,
        :price,
        :level,
        :language,
        :description,
        :short_description
      )
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to "You created this course. View analitycs", course_path(course)
      elsif course.enrollments.where(user: current_user).any?
        link_to "You bought this course. keep learning", course_path(course)
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: "btn btn-sm btn-success"
      else
        link_to "Free", new_course_enrollment_path(course), class: "btn btn-sm btn-success"
      end
      # logic to buy
    else
      link_to "Check Price", course_path(course),class: "btn btn-sm btn-success"
    end
  end
end

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  .card-body
    %small= simple_format(course.short_description)
  .card-footer
    .row
      .col-md-6
        .fa.fa-globe-africa
          = course.language
      .col-md-6
        .text-right
          .fa.fa-signal
          = course.level
  .card-footer
    .text-center
      = enrollment_button(course)
      /= number_to_currency(course.price)
  .card-footer
    .fa.fa-tasks
    = course.lessons.count
  .card-footer
    .row
      .col-md-6
        .far.fa-clock
        = course.created_at.strftime('%d-%b-%Y')
      .col-md-6
        .text-right
          .fa.fa-chalkboard-teacher
            /= User.find_by_id(course.user_id).email
          = link_to course.user.username, user_path(course.user)
  - if current_user
    - if policy(course).edit?
      .card-footer
        = link_to 'Edit', edit_course_path(course), class: 'btn btn-warning btn-sm'
        = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    = f.input :language, collection: Course.languages, include_blank: true
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
- content_for :title do
  ScolGeek
  \|
  Editing
  = @course.title

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
        Editing Course
    .card-body
      = render 'form'
    .card-footer
      = link_to 'Show', @course
      \|
      = link_to 'Back', courses_path(@course)

app/views/courses/index.html.haml
- content_for :title do
  ScolGeek
  \|
  All Courses
%p

%h3
  .text-center
    Courses
    .badge.badge-info
      = @courses.count
%p
.row
  .col-md-2
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      = f.label :title
      = f.search_field :title_or_short_description_cont, placeholder: 'Title', class: 'form-control form-control-sm'
      %br
      = f.label :description
      = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
      %br
      = f.label :languages
      = f.select :language_cont, Course.languages, placeholder: 'Language', class: 'form-control form-control-sm'
      %br
      %br
      = f.label :levels
      = f.select :level_cont, Course.levels, placeholder: 'Level', class: 'form-control form-control-sm'
      %br
      %br
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
      %br
      = f.label :Teacher
      = f.search_field :user_email_cont, placeholder: 'email', class: 'form-control form-control-sm'
      %br
      = f.submit class: 'btn btn-success btn-sm btn-block'
      %br
    .ml-2
    = link_to courses_path do
      Refresh
      .fa.fa-sync
  .col-md-10
    .card-columns
      - @courses.each do |course|
        = render 'courses/course', course: course
        %p
    != pagy_bootstrap_nav(@pagy)

app/views/courses/new.html.haml
- content_for :title do
  ScolGeek
  \|
  New Course

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      New course
    .card-body
      = render 'form'
    .card-footer
      = link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  ScolGeek
  \|
  = @course.title

%p
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p

.row
  .col-lg-6
    = render 'courses/course', course: @course
  .col-lg-6
    = link_to 'Add Lesson', new_lesson_path(@course, @lesson), class: 'btn btn-primary btn-sm btn-block'
    %p
    - @lessons.each do |lesson|
      = render 'lessons/lesson', lesson: lesson