config/routes.rb
Rails.application.routes.draw do

  resources :enrollments
  resources :lessons
  
  devise_for :users

  resources :courses do
    resources :enrollments, only: [:new, :create]
  end
  
  resources :users, only: [:index, :edit, :show, :update]

  get 'home/activity'

  root to: 'home#index'
end

app/views/layouts/_footer.html.haml
%br
%footer
  .container
    .row
      .col-md-4
        Copyright
        = Time.now.year
        &copy;
        Plataform SkolGeek
        .row
        .fa.fa-envelope
        = mail_to 'dtinivella@gmail.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Term and conditions
      .col-md-4
        About us
        .row
          = link_to 'Teach on SkolGeek', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-purple
  %a.navbar-brand{:href => "#"} <i class="fas fa-graduation-cap"></i> SkolGeek
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-user-graduate
              Courses

        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
              New Courses

        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
              Users

        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(enrollments_path)}"}
          = link_to enrollments_path, class: 'nav-link' do
            .fa.fa-lock-open
              Enrollment

      /SEARCH IN NAVBAR
      = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
        .input-group
          = f.search_field :title_or_short_description_cont, class:'form-control-sm', style:'float: left; width: 150px;', placeholder: "Find a course"
          %span.input-group-append
            %button.btn.btn-primary.btn-sm{:type => "submit"}
              %span.fa.fa-search{"aria-hidden" => "true"}

      %ul.navbar-nav.ml-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(home_activity_path)}"}
          = link_to home_activity_path, class: 'nav-link' do
            .fa.fa-bell
              Activity
          %li.nav-item
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %i.fa.fa-user
              %b= current_user.email
            .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              = link_to edit_user_registration_path,class:"dropdown-item" do
                .fa.fa-cog
                %b Account settings
              = link_to destroy_user_session_path, method: :delete, class:"dropdown-item" do
                .fa.fa-sign-out-alt
                %b Sign out
    - else
      %ul.navbar-nav.ml-auto
        %li.nav-item= link_to 'Registrer', new_user_registration_path, class: "btn btn-primary btn-sm"
        %p &nbsp;
        %li.nav-item= link_to 'Login', new_user_session_path, class: "btn btn-primary btn-sm"

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => 'alert'}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"}
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=devise-with, initias-scale=1.0", :name => "viewport" }/
    %title
      = content_for?(:title) ? yield(:title) : "ScolGeek"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.gstatic.com", :rel => "preconnect"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap", :rel => "stylesheet"}/
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
        = yield
      %br
  .bg-background
    = render 'layouts/footer'
    %div